#!/usr/bin/env bash

###############################################################
##           ___  _          _             
###         / _ \| | ___ __ | | __ _ _   _ 
####       | | | | |/ / '_ \| |/ _` | | | |
#####      | |_| |   <| |_) | | (_| | |_| |
######      \___/|_|\_\ .__/|_|\__,_|\__, |
#######               |_|            |___/   Generator © 2016
########
#########    Nabil Muhammad Firdaus (nabilftd@gmail.com)
###############################################################
###     ###     ###     ###     ###     ###     ###     ###
    ###     ###     ###     ###     ###     ###     ###     ###


realpath="$(pwd -P)"
generatorPath="${realpath}/pack/okplay/generator"

compile="$(javac -d ${generatorPath} ${generatorPath}/Generator.java)"
java -cp "$generatorPath" Generator "$realpath" $1 $2 $3 $4 $5 $6
