#!/usr/bin/env bash

realpath () {
    (
    TARGET_FILE="$1"

    cd "$(dirname "$TARGET_FILE")"
    TARGET_FILE=$(basename "$TARGET_FILE")

    COUNT=0
    while [ -L "$TARGET_FILE" -a $COUNT -lt 100 ]
    do
        TARGET_FILE=$(readlink "$TARGET_FILE")
        cd "$(dirname "$TARGET_FILE")"
        TARGET_FILE=$(basename "$TARGET_FILE")
        COUNT=$(($COUNT + 1))
    done

    if [ "$TARGET_FILE" == "." -o "$TARGET_FILE" == ".." ]; then
        cd "$TARGET_FILE"
        TARGET_FILEPATH=
    else
        TARGET_FILEPATH=/$TARGET_FILE
    fi

    # make sure we grab the actual windows path, instead of cygwin's path.
    if ! is_cygwin; then
        echo "$(pwd -P)/$TARGET_FILE"
    else
        echo $(cygwinpath "$(pwd -P)/$TARGET_FILE")
    fi
    )
}

# Uses uname to detect if we're in the odd cygwin environment.
is_cygwin() {
    local os=$(uname -s)
    case "$os" in
        CYGWIN*) return 0 ;;
        *)  return 1 ;;
    esac
}

# This can fix cygwin style /cygdrive paths so we get the
# windows style paths.
cygwinpath() {
    local file="$1"
    if is_cygwin; then
        echo $(cygpath -w $file)
    else
        echo $file
    fi
}

# List available colors
C_off='\033[0m'
Black='\033[0;30m'
Red='\033[0;31m'
Green='\033[0;32m'
Yellow='\033[0;33m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
White='\033[0;37m'

####/
 ##/
 #/ Function for generate Play Controller.
#####/
generatePlayController() {
    ctrl_path="app/controllers/"
    ctrl_stub="pack/okplay/generator/stubs/Controller.stub"
    new_ctrl="$realpath$ctrl_path$1.java"
    run="$(cp $realpath$ctrl_stub $new_ctrl)"
    run="$(sed -i 's|Generator_Controller_Name|'"$1"'|g' $new_ctrl)"
    echo "New controller has been created"
}

####/
 ##/
 #/ Function for generate Play Model.
#####/
generatePlayModel() {
    model_path="app/models/"
    model_stub="pack/okplay/generator/stubs/Model.stub"
    new_model="$realpath$model_path$1.java"
    run="$(cp $realpath$model_stub $new_model)"
    run="$(sed -i 's|Generator_Model_Name|'"$1"'|g' $new_model)"
    echo "New model has been created"
}

####/
 ##/
 #/ Funtion for display Okplay helper.
#####/
helper() {
    printf "$Green%s$C_off %s $Cyan%s\n" "Play Framework" "version" "2.5.3 (Streamy)"
    printf "\n"
    printf ""
    run=$(mkdir coba && rm -r coba)
    printf "$run"
}
